{% set version = "1.16.1" %}
{% set major = version.split('.')[0] %}
{% set minor = version.split('.')[1] %}
{% set patch = version.split('.')[2] %}
package:
  name: c-ares
  version: {{ version }}

source:
  url: https://github.com/c-ares/c-ares/releases/download/cares-{{ major }}_{{ minor }}_{{ patch }}/c-ares-{{ version }}.tar.gz
  sha256: d08312d0ecc3bd48eee0a4cc0d2137c9f194e0a28de2028928c0f6cae85f86ce

build:
  number: 0  

outputs:
  - name: c-ares
    script: build_output.sh  # [unix]
    script: bld_output.bat  # [win]
    build:
      run_exports:
      - {{ pin_subpackage("c-ares", max_pin="x") }}
    requirements:
      build:
        - {{ compiler("c") }}
        - cmake  
        # cmake on unix depends on c-ares. This breaks the cycle.
        # - cmake-no-system  # [unix]
        - ninja  # [unix]
      run_constraint:
        - c-ares-static <0a0
    test:
      commands:
        - test -f ${PREFIX}/include/ares.h            # [not win]
        - test -f ${PREFIX}/lib/libcares${SHLIB_EXT}  # [not win]
        - test ! -f ${PREFIX}/lib/libcares.a          # [not win]
        - test ! -f ${PREFIX}/lib/libcares_static.a   # [not win]
        - if not exist %PREFIX%\\Library\\include\\ares.h exit 1  # [win]
        - if not exist %PREFIX%\\Library\\bin\\cares.dll exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\cares.lib exit 1  # [win]
        - if exist %PREFIX%\\Library\\lib\\cares_static.lib exit 1  # [win]
  - name: c-ares-static
    script: build_output.sh  # [unix]
    script: bld_output.bat  # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - cmake  
        # cmake on unix depends on c-ares. This breaks the cycle.
        # - cmake-no-system  # [unix]
        - ninja  # [unix]
      run_constraint:
        - c-ares <0a0
    test:
      commands:
        - test -f ${PREFIX}/lib/libcares.a  # [not win]
        - test ! -f ${PREFIX}/lib/libcares${SHLIB_EXT}  # [not win]
        - test -f ${PREFIX}/include/ares.h            # [not win]
        - if not exist %PREFIX%\\Library\\include\\ares.h exit 1  # [win]
        - if exist %PREFIX%\\Library\\bin\\cares.dll exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\cares.lib exit 1  # [win]

about:
  home: https://c-ares.haxx.se/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: This is c-ares, an asynchronous resolver library

extra:
  recipe-maintainers:
    - ocefpaf
    - wesm
    - xhochy
